#!/usr/bin/env bash
# monitor.sh - Linux server monitoring dashboard generator
# Generates report.html and a timestamped log in logs/

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUTPUT_HTML="report.html"
CSS_FILE="style.css"
LOG_DIR="logs"

if [[ ! -f "$SCRIPT_DIR/$CSS_FILE" ]]; then
  echo "Error: $CSS_FILE not found in $SCRIPT_DIR"
  exit 1
fi

DATE="$(date '+%Y-%m-%d %H:%M:%S %Z')"
HOSTNAME="$(hostname -s)"
UPTIME="$(uptime -p 2>/dev/null || uptime)"
KERNEL="$(uname -sr)"

CPU_LOAD="$(cat /proc/loadavg | awk '{print $1 " " $2 " " $3}')"
CPU_MODEL="$(grep -m1 'model name' /proc/cpuinfo 2>/dev/null | cut -d: -f2- | sed 's/^ //' || echo 'N/A')"
CPU_COUNT="$(grep -c '^processor' /proc/cpuinfo 2>/dev/null || echo 'N/A')"

MEM_TOTAL="$(free -h | awk '/^Mem:/ {print $2}')"
MEM_USED="$(free -h | awk '/^Mem:/ {print $3}')"
MEM_FREE="$(free -h | awk '/^Mem:/ {print $4}')"

DISK_SUMMARY="$(df -h --output=target,size,used,avail,pcent | tail -n +2 | sed 's/$/<\/td><\/tr>/' | sed 's/^/<tr><td>/' | sed 's/  */<\/td><td>/g')"

TOP_PROCESSES="$(ps -eo pid,comm,%cpu,%mem --sort=-%cpu | head -n 6)"

mkdir -p "$SCRIPT_DIR/$LOG_DIR"

cat > "$SCRIPT_DIR/$OUTPUT_HTML" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Linux Server Monitor Report</title>
  <link rel="stylesheet" href="$CSS_FILE" />
</head>
<body>
  <header>
    <h1>Linux Server Monitor</h1>
    <p>Generated on $DATE for host <strong>$HOSTNAME</strong></p>
  </header>

  <section>
    <h2>System Overview</h2>
    <dl>
      <dt>Hostname</dt><dd>$HOSTNAME</dd>
      <dt>Date</dt><dd>$DATE</dd>
      <dt>Uptime</dt><dd>$UPTIME</dd>
      <dt>Kernel</dt><dd>$KERNEL</dd>
      <dt>CPU</dt><dd>$CPU_MODEL ($CPU_COUNT cores)</dd>
      <dt>Load Average</dt><dd>$CPU_LOAD</dd>
      <dt>Memory</dt><dd>$MEM_USED / $MEM_TOTAL used, $MEM_FREE free</dd>
    </dl>
  </section>

  <section>
    <h2>Disk Usage</h2>
    <table>
      <thead>
        <tr><th>Mount</th><th>Size</th><th>Used</th><th>Avail</th><th>Use%</th></tr>
      </thead>
      <tbody>
        $DISK_SUMMARY
      </tbody>
    </table>
  </section>

  <section>
    <h2>Top Processes</h2>
    <pre>$TOP_PROCESSES</pre>
  </section>

  <footer>
    <p>Generated by <code>monitor.sh</code></p>
  </footer>
</body>
</html>
EOF

chmod 644 "$SCRIPT_DIR/$OUTPUT_HTML"

# Write a timestamped log for each run
LOG_FILE="$SCRIPT_DIR/$LOG_DIR/monitor-$(date '+%Y%m%d-%H%M%S').log"
cat > "$LOG_FILE" <<LOGEOF
Dashboard Generated Successfully
Time: $DATE
Hostname: $HOSTNAME

Uptime: $UPTIME
Kernel: $KERNEL
CPU Load: $CPU_LOAD
Memory: $MEM_USED / $MEM_TOTAL used, $MEM_FREE free

Top Processes:
$TOP_PROCESSES
LOGEOF

chmod 644 "$LOG_FILE"

echo "Report written to $OUTPUT_HTML"
echo "Log written to $LOG_FILE"
